name: CI

on:
  push:
    brances: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Grand execute permission for gradlew
        run: chmond +x gradlew
      - name: Run Backend Tests
        run: ./gradlew test